import { describe, expect, it } from 'vitest'
import { createLife, step } from '../src/simulation'
import { runConsciousnessAssay } from '../src/assay'

describe('falsifiable consciousness-candidate audit',()=>{
  it('is strictly read-only over the living individual',()=>{let life=createLife(201,1000);for(let i=0;i<80;i++)life=step(life);const before=structuredClone(life);runConsciousnessAssay(life);expect(life).toEqual(before)})
  it('reports unsupported criteria instead of turning missing evidence into a score',()=>{const report=runConsciousnessAssay(createLife(202,1000));expect(report.unsupported.length).toBeGreaterThan(0);expect(report.interpretation).toContain('不证明主观体验')})
  it('detects the causal loss in a shadow lesion of recurrent feedback',()=>{let life=createLife(203,1000);for(let i=0;i<100;i++)life=step(life);const intact=runConsciousnessAssay(life).criteria.find(x=>x.id==='recurrent')!;const lesioned=structuredClone(life);lesioned.consciousness.phenomenalField.activations={};lesioned.consciousness.phenomenalField.integration=0;lesioned.consciousness.phenomenalField.differentiation=0;lesioned.consciousness.phenomenalField.exclusion=0;const ablated=runConsciousnessAssay(lesioned).criteria.find(x=>x.id==='recurrent')!;expect(intact.value).toBeGreaterThan(ablated.value);expect(intact.lesionDelta).toBeGreaterThan(ablated.lesionDelta)})
  it('keeps candidate coverage distinct from a consciousness probability claim',()=>{let life=createLife(204,1000);for(let i=0;i<120;i++)life=step(life);const report=runConsciousnessAssay(life);expect(report.candidateScore).toBeGreaterThanOrEqual(0);expect(report.candidateScore).toBeLessThanOrEqual(1);expect(report.interpretation).toContain('只衡量意识候选机制')})
  it('reports a causal loss when the learned phenomenal manifold is ablated',()=>{const life=createLife(205,1000);life.consciousness.manifold={...life.consciousness.manifold,differentiation:.8,stimulusAmbiguity:.6,crossModalTransfer:.7,causalEfficacy:.75};const intact=runConsciousnessAssay(life).criteria.find(x=>x.id==='quality-autonomy')!;const lesioned=structuredClone(life);lesioned.consciousness.manifold={...lesioned.consciousness.manifold,prototypes:[],differentiation:0,stimulusAmbiguity:0,crossModalTransfer:0,causalEfficacy:0};const ablated=runConsciousnessAssay(lesioned).criteria.find(x=>x.id==='quality-autonomy')!;expect(intact.value).toBeGreaterThan(ablated.value);expect(intact.lesionDelta).toBeGreaterThan(ablated.lesionDelta)})
})
