import { describe, expect, it } from 'vitest'
import { createLife } from '../src/simulation'
import { loadLife, saveLife, SnapshotError, STORAGE_KEY } from '../src/persistence'

class MemoryStorage implements Storage{private m=new Map<string,string>();get length(){return this.m.size}clear(){this.m.clear()}getItem(k:string){return this.m.get(k)??null}key(i:number){return [...this.m.keys()][i]??null}removeItem(k:string){this.m.delete(k)}setItem(k:string,v:string){this.m.set(k,v)}}
describe('snapshot persistence',()=>{
  it('preserves identity',()=>{const s=new MemoryStorage(),life=createLife(123,Date.now());saveLife(life,s);expect(loadLife(s)?.id).toBe(life.id)})
  it('refuses damaged data without overwriting it',()=>{const s=new MemoryStorage();s.setItem(STORAGE_KEY,'{broken');expect(()=>loadLife(s)).toThrow(SnapshotError);expect(s.getItem(STORAGE_KEY)).toBe('{broken')})
  it('migrates a v1 life into the conscious architecture',()=>{const s=new MemoryStorage(),life=createLife(7,Date.now());const legacy={...life};delete (legacy as Partial<typeof life>).consciousness;s.setItem(STORAGE_KEY,JSON.stringify({version:1,savedAt:Date.now(),life:legacy}));const loaded=loadLife(s);expect(loaded?.consciousness.workspace.background).toEqual([]);expect(loaded?.id).toBe(life.id)})
  it('removes migration-created zero-energy goals without erasing learned models',()=>{const s=new MemoryStorage(),life=createLife(8,Date.now());delete (life.consciousness as Partial<typeof life.consciousness>).architectureVersion;life.consciousness.preferredSetpoints.energy=0;life.consciousness.goals=[{id:'bad',dimension:'energy',target:0,urgency:1,persistence:1,evidence:99,bornTick:1}];life.consciousness.causalModels.rest.samples=12;s.setItem(STORAGE_KEY,JSON.stringify({version:2,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.consciousness.preferredSetpoints.energy).toBeGreaterThan(.5);expect(loaded.consciousness.goals).toHaveLength(0);expect(loaded.consciousness.causalModels.rest.samples).toBe(12)})
it('migrates an older life with an independent other and social model',()=>{const s=new MemoryStorage(),life=createLife(9,Date.now());delete (life.environment as Partial<typeof life.environment>).other;delete (life.consciousness as Partial<typeof life.consciousness>).social;s.setItem(STORAGE_KEY,JSON.stringify({version:6,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.environment.other.hidden.energy).toBeGreaterThan(0);expect(loaded.consciousness.social.samples).toBe(0);expect(loaded.consciousness.architectureVersion).toBe(21)})
  it('adds perspective-taking fields to a v7 social model',()=>{const s=new MemoryStorage(),life=createLife(10,Date.now());delete (life.consciousness.social as Partial<typeof life.consciousness.social>).attributedResources;delete (life.consciousness.social as Partial<typeof life.consciousness.social>).jointAttention;s.setItem(STORAGE_KEY,JSON.stringify({version:7,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.consciousness.social.attributedResources).toEqual([]);expect(loaded.consciousness.social.jointAttention).toBe(0)})
  it('adds an attention schema to a v8 life',()=>{const s=new MemoryStorage(),life=createLife(11,Date.now());delete (life.consciousness as Partial<typeof life.consciousness>).attentionSchema;s.setItem(STORAGE_KEY,JSON.stringify({version:8,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.consciousness.attentionSchema.samples).toBe(0);expect(loaded.consciousness.architectureVersion).toBe(21)})
  it('adds a recurrent phenomenal field to a v9 life',()=>{const s=new MemoryStorage(),life=createLife(12,Date.now());delete (life.consciousness as Partial<typeof life.consciousness>).phenomenalField;s.setItem(STORAGE_KEY,JSON.stringify({version:9,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.consciousness.phenomenalField.activations).toEqual({});expect(loaded.consciousness.architectureVersion).toBe(21)})
  it('adds endogenous dreaming to a v10 life',()=>{const s=new MemoryStorage(),life=createLife(13,Date.now());delete (life.consciousness as Partial<typeof life.consciousness>).dream;s.setItem(STORAGE_KEY,JSON.stringify({version:10,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.consciousness.dream.mode).toBe('wake');expect(loaded.consciousness.architectureVersion).toBe(21)})
  it('adds experiential value learning to a v11 life',()=>{const s=new MemoryStorage(),life=createLife(14,Date.now());delete (life.consciousness as Partial<typeof life.consciousness>).affect;s.setItem(STORAGE_KEY,JSON.stringify({version:11,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.consciousness.affect.experientialValues).toEqual({});expect(loaded.consciousness.architectureVersion).toBe(21)})
  it('adds a first-person lexicon to a v12 life',()=>{const s=new MemoryStorage(),life=createLife(15,Date.now());delete (life.consciousness as Partial<typeof life.consciousness>).introspection;s.setItem(STORAGE_KEY,JSON.stringify({version:12,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.consciousness.introspection.clusters).toEqual([]);expect(loaded.consciousness.architectureVersion).toBe(21)})
  it('adds efference-copy models to a v13 life',()=>{const s=new MemoryStorage(),life=createLife(16,Date.now());delete (life.consciousness as Partial<typeof life.consciousness>).efference;s.setItem(STORAGE_KEY,JSON.stringify({version:13,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.consciousness.efference.models.explore.samples).toBe(0);expect(loaded.consciousness.architectureVersion).toBe(21)})
  it('adds predictive semantics to v14 private glyphs',()=>{const s=new MemoryStorage(),life=createLife(17,Date.now());life.consciousness.introspection.clusters=[{id:1,centroid:Array(11).fill(.5),count:8,variance:.1,stability:.7,lastTick:1,glyph:'ϟ'} as never];s.setItem(STORAGE_KEY,JSON.stringify({version:14,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.consciousness.introspection.clusters[0].forecast).toHaveLength(11);expect(loaded.consciousness.introspection.clusters[0].predictiveConfidence).toBe(0);expect(loaded.consciousness.architectureVersion).toBe(21)})
  it('adds adaptive attention effort to a v15 life',()=>{const s=new MemoryStorage(),life=createLife(18,Date.now());delete (life.consciousness.attentionSchema as Partial<typeof life.consciousness.attentionSchema>).effort;delete (life.consciousness.attentionSchema as Partial<typeof life.consciousness.attentionSchema>).cumulativeCost;s.setItem(STORAGE_KEY,JSON.stringify({version:15,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.consciousness.attentionSchema.effort).toBe(.25);expect(loaded.consciousness.attentionSchema.cumulativeCost).toBe(0);expect(loaded.consciousness.architectureVersion).toBe(21)})
  it('adds a subjective spatial model to a v16 life',()=>{const s=new MemoryStorage(),life=createLife(19,Date.now());delete (life.consciousness as Partial<typeof life.consciousness>).spatial;s.setItem(STORAGE_KEY,JSON.stringify({version:16,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.consciousness.spatial.x).toBe(life.position.x);expect(loaded.consciousness.spatial.landmarks).toEqual([]);expect(loaded.consciousness.architectureVersion).toBe(21)})
  it('adds intersubjective communication to a v17 life',()=>{const s=new MemoryStorage(),life=createLife(20,Date.now());delete (life.consciousness as Partial<typeof life.consciousness>).communication;s.setItem(STORAGE_KEY,JSON.stringify({version:17,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.consciousness.communication.associations).toEqual({});expect(loaded.consciousness.communication.lastResponse).toBe('none');expect(loaded.consciousness.architectureVersion).toBe(21)})
  it('adds autonomous repair fields to a v19 communication model',()=>{const s=new MemoryStorage(),life=createLife(22,Date.now());life.consciousness.communication.associations['ϟ']={attempts:2,responses:1,efficacy:.4} as never;delete (life.consciousness.communication as Partial<typeof life.consciousness.communication>).mutualGrounding;delete (life.environment.other.hidden as Partial<typeof life.environment.other.hidden>).lastEchoTick;s.setItem(STORAGE_KEY,JSON.stringify({version:19,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.consciousness.communication.mutualGrounding).toBe(0);expect(loaded.consciousness.communication.associations['ϟ'].repairs).toBe(0);expect(loaded.environment.other.hidden.lastEchoTick).toBe(-1)})
  it('adds an organismic boundary without replacing a v20 individual',()=>{const s=new MemoryStorage(),life=createLife(23,Date.now());delete (life.consciousness as Partial<typeof life.consciousness>).organismic;s.setItem(STORAGE_KEY,JSON.stringify({version:20,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.id).toBe(life.id);expect(loaded.consciousness.organismic.membraneIntegrity).toBeGreaterThan(0);expect(loaded.consciousness.architectureVersion).toBe(21)})
  it('adds a phenomenal manifold without replacing a v21 individual',()=>{const s=new MemoryStorage(),life=createLife(24,Date.now());delete (life.consciousness as Partial<typeof life.consciousness>).manifold;s.setItem(STORAGE_KEY,JSON.stringify({version:21,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.id).toBe(life.id);expect(loaded.consciousness.manifold.prototypes).toEqual([]);expect(loaded.consciousness.architectureVersion).toBe(21)})
  it('adds an independent glyph learner to a v18 other',()=>{const s=new MemoryStorage(),life=createLife(21,Date.now());delete (life.environment.other.hidden as Partial<typeof life.environment.other.hidden>).glyphModels;delete (life.environment.other.hidden as Partial<typeof life.environment.other.hidden>).lastPulseTick;delete (life.environment.other.hidden as Partial<typeof life.environment.other.hidden>).lastObservedMainTick;s.setItem(STORAGE_KEY,JSON.stringify({version:18,savedAt:Date.now(),life}));const loaded=loadLife(s)!;expect(loaded.environment.other.hidden.glyphModels).toEqual({});expect(loaded.environment.other.hidden.lastPulseTick).toBe(-1);expect(loaded.id).toBe(life.id)})
})
