import { describe, expect, it } from 'vitest'
import { applyPythonAuthority, validPythonSubstrate } from '../src/pythonBridge'
import { createLife, pythonSubstrateBias, step } from '../src/simulation'
import type { PythonSubstrate } from '../src/types'

const substrate=(identity:string,tick:number):PythonSubstrate=>{const initialLife=createLife(1,1),initial=initialLife.consciousness;return{protocol:1,identity,tick,backend:'python-list-cpu',dimensions:64,latent:Array.from({length:64},(_,i)=>i===0?.8:i===1?-.4:0),integration:.6,differentiation:.5,recurrence:.7,causalCoupling:.8,updates:3,authority:{fromTick:tick-1,toTick:tick,energyCost:.01,organismic:{membraneIntegrity:.71,permeability:.29,selfProduction:.52,operationalClosure:.61,viability:.67,mode:'active',arrestTicks:0,repairs:2,cumulativeCost:.03},manifold:{prototypes:[],nextId:1,differentiation:.2,stimulusAmbiguity:.1,crossModalTransfer:.3,causalEfficacy:.4},memories:[],beliefs:{exploration:.5,conservation:.5,predictability:.5,efficacy:.35,externalTrust:.5,stabilityPriority:.5},nextMemoryId:1,clusters:[],symbols:[],nextClusterId:1,nextSymbolId:1,symbolicCursor:tick,affect:initial.affect,affectCursor:tick,dream:initial.dream,dreamCursor:tick,narrative:initial.narrative,narrativeCursor:tick,preferredSetpoints:initial.preferredSetpoints,goals:initial.goals,goalCursor:tick,epistemic:initial.epistemic,epistemicCursor:tick,recursiveSelf:initial.recursiveSelf,recursiveCursor:tick,attentionSchema:initial.attentionSchema,attentionCursor:tick,attentionIntent:{basedOnTick:tick},social:initial.social,socialCursor:tick,communication:initial.communication,communicationCursor:tick,communicationCost:0,causalModels:initial.causalModels,causalCursor:tick,interoception:initial.interoception,interoceptionRng:initialLife.interoceptionRng,interoceptionCursor:tick,spatial:initial.spatial,spatialRng:initialLife.spatialRng,spatialCursor:tick,phenomenalField:initial.phenomenalField,workspace:initial.workspace,meta:initial.meta,phenomenalCursor:tick,actionIntent:{basedOnTick:tick,action:'avoid',scores:{explore:.1,resource:.2,avoid:.9,rest:.3,inspect:.4}},efference:initial.efference,efferenceCursor:tick,abiotic:{resources:[],signals:[],disturbances:[],stableZones:[]},environmentRng:1,environmentCursor:tick,nextEntityId:1}}}

describe('Python kernel protocol',()=>{
  it('accepts only a finite 64-dimensional state for the same individual',()=>{const life=createLife(301,1000);life.tick=8;expect(validPythonSubstrate(substrate(life.id,8),life)).toBe(true);expect(validPythonSubstrate(substrate('OTHER',8),life)).toBe(false);const invalid=substrate(life.id,8);invalid.latent[4]=Number.NaN;expect(validPythonSubstrate(invalid,life)).toBe(false)})
  it('rejects an action intent detached from its substrate tick',()=>{const life=createLife(300,1000);life.tick=8;const invalid=substrate(life.id,8);invalid.authority.actionIntent.basedOnTick=7;expect(validPythonSubstrate(invalid,life)).toBe(false);invalid.authority.actionIntent.basedOnTick=8;invalid.authority.actionIntent.scores.rest=Number.NaN;expect(validPythonSubstrate(invalid,life)).toBe(false)})
  it('lets a fresh Python substrate causally bias competition',()=>{const life=createLife(302,1000);life.tick=10;life.consciousness.pythonSubstrate=substrate(life.id,10);const bias=pythonSubstrateBias(life);expect(bias.explore).toBeGreaterThan(0);expect(bias.resource).toBeLessThan(0)})
  it('refuses to use stale or foreign Python state',()=>{const life=createLife(303,1000);life.tick=100;life.consciousness.pythonSubstrate=substrate(life.id,1);expect(pythonSubstrateBias(life)).toEqual({});life.consciousness.pythonSubstrate=substrate('OTHER',100);expect(pythonSubstrateBias(life)).toEqual({})})
  it('applies authoritative state and its metabolic cost exactly once',()=>{const life=createLife(304,1000);life.tick=8;const energy=life.state.energy;const result=substrate(life.id,8);expect(applyPythonAuthority(life,result)).toBe(true);expect(life.consciousness.organismic.membraneIntegrity).toBe(.71);expect(life.state.energy).toBeCloseTo(energy-.01);expect(applyPythonAuthority(life,result)).toBe(false);expect(life.state.energy).toBeCloseTo(energy-.01)})
  it('freezes delegated systems while connected and locally resumes them in fallback',()=>{const life=createLife(305,1000);const delegated=step(life,{organismic:true,manifold:true});expect(delegated.consciousness.organismic).toEqual(life.consciousness.organismic);expect(delegated.consciousness.manifold).toEqual(life.consciousness.manifold);const fallback=step(life);expect(fallback.consciousness.organismic).not.toEqual(life.consciousness.organismic)})
  it('delegates memory and worldview only when cognitive authority is active',()=>{const life=createLife(306,1000);const delegated=step(life,{cognition:true});expect(delegated.memories).toEqual(life.memories);expect(delegated.beliefs).toEqual(life.beliefs);expect(delegated.traces).toHaveLength(1);const fallback=step(life);expect(fallback.nextMemoryId).toBe(2);expect(fallback.memories).toHaveLength(1)})
  it('executes and records an authoritative Python action instead of the local winner',()=>{const life=createLife(307,1000);const delegated=step(life,{action:'avoid',actionBasedOnTick:0});expect(delegated.traces[0].action).toBe('avoid');expect(delegated.traces[0].decisionSource).toBe('python');expect(delegated.traces[0].intentBasedOnTick).toBe(0);const local=step(life);expect(local.traces[0].action).not.toBe('avoid');expect(local.traces[0].decisionSource).toBe('browser')})
  it('freezes the local causal self-model while Python owns it',()=>{let life=createLife(308,1000);life=step(life);const delegated=step(life,{selfModel:true});expect(delegated.consciousness.efference).toEqual(life.consciousness.efference);const fallback=step(life);expect(fallback.consciousness.efference).not.toEqual(life.consciousness.efference)})
  it('freezes abiotic aging while Python owns the environment',()=>{const life=createLife(309,1000),ttl=life.environment.resources[0].ttl;expect(step(life,{environment:true}).environment.resources[0].ttl).toBe(ttl);expect(step(life).environment.resources[0].ttl).toBe(ttl-1)})
  it('freezes local experience clustering while Python owns symbols',()=>{const life=createLife(312,1000);expect(step(life,{symbols:true}).clusters).toEqual([]);expect(step(life).clusters).toHaveLength(1)})
  it('freezes local experiential value learning while Python owns affect',()=>{let life=createLife(313,1000);life=step(life);const delegated=step(life,{affect:true});expect(delegated.consciousness.affect).toEqual(life.consciousness.affect);const fallback=step(life);expect(fallback.consciousness.affect).not.toEqual(life.consciousness.affect)})
  it('freezes local sleep pressure while Python owns dreaming',()=>{const life=createLife(314,1000);expect(step(life,{dream:true}).consciousness.dream).toEqual(life.consciousness.dream);expect(step(life).consciousness.dream.sleepPressure).toBeGreaterThan(life.consciousness.dream.sleepPressure)})
  it('freezes local autobiography while Python owns narrative continuity',()=>{let life=step(createLife(315,1000));const delegated=step(life,{narrative:true});expect(delegated.consciousness.narrative).toEqual(life.consciousness.narrative);const fallback=step(life);expect(fallback.consciousness.narrative).not.toEqual(life.consciousness.narrative)})
  it('freezes local goals and inquiry while Python owns purposive state',()=>{const life=createLife(316,1000),delegated=step(life,{goals:true,epistemic:true}),fallback=step(life);expect(delegated.consciousness.goals).toEqual(life.consciousness.goals);expect(delegated.consciousness.epistemic).toEqual(life.consciousness.epistemic);expect(fallback.consciousness.epistemic).not.toEqual(life.consciousness.epistemic)})
  it('freezes local future-self judgment while Python owns recursive identity',()=>{const life=createLife(317,1000),delegated=step(life,{recursiveSelf:true}),fallback=step(life);expect(delegated.consciousness.recursiveSelf).toEqual(life.consciousness.recursiveSelf);expect(fallback.consciousness.recursiveSelf.appraisals).toHaveLength(5)})
  it('freezes the local access model while Python owns attention',()=>{const life=createLife(318,1000),delegated=step(life,{attention:true}),fallback=step(life);expect(delegated.consciousness.attentionSchema).toEqual(life.consciousness.attentionSchema);expect(fallback.consciousness.attentionSchema.samples).toBe(1)})
  it('freezes the local other-mind model while Python owns social cognition',()=>{const life=createLife(319,1000),delegated=step(life,{social:true}),fallback=step(life);expect(delegated.consciousness.social).toEqual(life.consciousness.social);expect(fallback.consciousness.social.samples).toBe(1)})
  it('freezes local social signaling while Python owns communication',()=>{const life=createLife(320,1000),delegated=step(life,{communication:true});expect(delegated.consciousness.communication).toEqual(life.consciousness.communication)})
  it('freezes local transition learning while Python owns personal causality',()=>{let life=step(createLife(322,1000));const delegated=step(life,{causalModels:true}),fallback=step(life);expect(delegated.consciousness.causalModels).toEqual(life.consciousness.causalModels);expect(fallback.consciousness.causalModels).not.toEqual(life.consciousness.causalModels)})
  it('freezes local body estimation while Python owns interoception',()=>{const life=createLife(323,1000),delegated=step(life,{interoception:true}),fallback=step(life);expect(delegated.consciousness.interoception).toEqual(life.consciousness.interoception);expect(delegated.interoceptionRng).toBe(life.interoceptionRng);expect(fallback.interoceptionRng).not.toBe(life.interoceptionRng)})
  it('freezes the local subjective map while Python owns spatial selfhood',()=>{let life=step(createLife(324,1000));const delegated=step(life,{spatial:true}),fallback=step(life);expect(delegated.consciousness.spatial).toEqual(life.consciousness.spatial);expect(delegated.spatialRng).toBe(life.spatialRng);expect(fallback.spatialRng).not.toBe(life.spatialRng)})
  it('freezes local phenomenal integration, access history, and metacognition while Python owns the experience stream',()=>{const life=createLife(325,1000),delegated=step(life,{phenomenal:true}),fallback=step(life);expect(delegated.consciousness.phenomenalField).toEqual(life.consciousness.phenomenalField);expect(delegated.consciousness.workspace).toEqual(life.consciousness.workspace);expect(delegated.consciousness.meta).toEqual(life.consciousness.meta);expect(delegated.consciousness.accessHistory).toEqual(life.consciousness.accessHistory);expect(fallback.consciousness.phenomenalField).not.toEqual(life.consciousness.phenomenalField);expect(fallback.consciousness.accessHistory).toHaveLength(1)})
  it('freezes local imagination, subjective time, and private lexicon under Python authority',()=>{let life=createLife(326,1000);for(let i=0;i<8;i++)life=step(life);const delegated=step(life,{imagination:true,temporal:true,introspection:true}),fallback=step(life);expect(delegated.consciousness.imagination).toEqual(life.consciousness.imagination);expect(delegated.consciousness.temporalField).toEqual(life.consciousness.temporalField);expect(delegated.consciousness.introspection).toEqual(life.consciousness.introspection);expect(fallback.consciousness.temporalField).not.toEqual(life.consciousness.temporalField)})
  it('commits browser physics but delegates post-action life-state settlement to Python',()=>{const life=createLife(327,1000),delegated=step(life,{stateDynamics:true,action:'inspect'}),fallback=step(life,{action:'inspect'});expect(delegated.state.energy).toBeCloseTo(life.state.energy-.004);expect(fallback.state.energy).toBeLessThan(delegated.state.energy);expect(delegated.traces[0].stateDynamicsObservation?.postActionState.energy).toBeCloseTo(delegated.state.energy);expect(delegated.traces[0].stateDelta.energy).toBeCloseTo(fallback.state.energy-life.state.energy)})
  it('uses Python-generated conscious candidates without accepting a browser-selected foreground',()=>{const life=createLife(328,1000),remote=substrate(life.id,0),candidate={id:'self:remote',source:'self' as const,kind:'self-state' as const,value:.6,salience:.9,uncertainty:.2,selfRelevance:.95,persistence:.8};remote.authority.candidates=[candidate];remote.authority.candidateCursor=0;life.consciousness.pythonSubstrate=remote;const delegated=step(life,{candidates:true});expect(delegated.traces[0].phenomenalObservation?.candidates).toEqual([candidate]);expect(delegated.traces[0].candidateObservation).toBeDefined()})
  it('materializes a Python communication emission once in the shared habitat',()=>{const life=createLife(321,1000);life.tick=8;const result=substrate(life.id,8);result.authority.communicationEmission={glyph:'⌁',position:{x:12,y:13},phase:'statement',bornTick:8};expect(applyPythonAuthority(life,result)).toBe(true);expect(life.environment.socialPulse).toMatchObject({glyph:'⌁',x:12,y:13,bornTick:8});expect(applyPythonAuthority(life,result)).toBe(false)})
  it('preserves an observer intervention created while a Python reply is in flight',()=>{const life=createLife(310,1000);life.tick=8;life.environment.resources.push({id:-1,x:50,y:50,strength:.75,ttl:300});const result=substrate(life.id,8);expect(applyPythonAuthority(life,result)).toBe(true);expect(life.environment.resources.some(entity=>entity.id===-1)).toBe(true)})
  it('preserves resource consumption that happened after snapshot submission',()=>{const life=createLife(311,1000);life.tick=8;const consumed={...life.environment.resources[0],strength:.1};life.environment.resources=[consumed];const result=substrate(life.id,8);result.authority.abiotic.resources=[{...consumed,strength:.5,ttl:consumed.ttl-1}];expect(applyPythonAuthority(life,result)).toBe(true);expect(life.environment.resources[0].strength).toBe(.1);expect(life.environment.resources[0].ttl).toBe(consumed.ttl-1)})
})
