import './style.css'
import { actionLabel, createLife, intervene, perceive, recallEgocentricScene, senseEgocentricScene, step } from './simulation'
import { exportSnapshot, importSnapshot, loadLife, saveLife, SnapshotError } from './persistence'
import type { Beliefs, Intervention, Life, StateVector } from './types'
import { contentLabels } from './consciousness'
import { runConsciousnessAssay } from './assay'

const app=document.querySelector<HTMLDivElement>('#app')!
let life:Life, running=true, speed=1, selectedTraceId=0, lastFrame=performance.now(), accumulator=0, saveCounter=0, warningRaw=''
try{life=loadLife()??createLife()}catch(e){warningRaw=e instanceof SnapshotError?e.raw:'';life=createLife(0xE1EC7A);running=false}

const stateLabels:Record<keyof StateVector,string>={energy:'能量',integrity:'完整度',arousal:'激活度',uncertainty:'不确定性',coherence:'自洽度',curiosity:'探索倾向',agency:'能动归因',valence:'状态利度'}
const beliefLabels:Record<keyof Beliefs,string>={exploration:'探索',conservation:'保守',predictability:'可预测',efficacy:'行动有效',externalTrust:'外部可信',stabilityPriority:'稳定优先'}
const interventionLabels:Record<Intervention,string>={resource:'投放资源',signal:'投放未知信号',disturbance:'制造扰动'}
const fmt=(v:number)=>Math.round(v*100)
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))

function shell(){
  app.innerHTML=`<main class="app"><header class="topbar"><div><div class="eyebrow">Autopoietic substrate / v0.25 · phenomenal-manifold</div><h1 class="title">电子生命培养皿</h1></div><div class="identity"><strong id="life-id"></strong><small id="age"></small></div></header>
  <section class="layout"><aside class="left">
    <div class="panel"><h2>时间控制</h2><div class="controls"><button id="toggle"></button>${[1,5,20].map(x=>`<button class="speed" data-speed="${x}">${x}×</button>`).join('')}</div></div>
    <div class="panel"><h2>环境干预</h2><div class="interventions">${(['resource','signal','disturbance'] as Intervention[]).map(k=>`<button class="intervention" data-intervention="${k}"><span>${interventionLabels[k]}</span><small></small></button>`).join('')}</div></div>
    <div class="panel"><h2>内部动力</h2><div id="meters"></div></div>
    <div class="panel"><h2>状态轨迹</h2><canvas class="chart" id="chart"></canvas></div>
  </aside><section class="panel dish-panel"><div class="dish-header"><span class="eyebrow">Closed digital habitat</span><span class="tick" id="tick"></span></div><div class="dish-wrap"><canvas class="dish" id="dish"></canvas><div class="legend"><span><i class="dot" style="background:#80e0b2"></i>资源</span><span><i class="dot" style="background:#81a9ff"></i>未知信号</span><span><i class="dot" style="background:#e57d72"></i>扰动</span><span><i class="dot" style="background:#bea96b"></i>稳定区</span></div></div><div class="subjective-grid"><div class="subjective-cell"><h2>主观场 / 前景</h2><div id="workspace"></div></div><div class="subjective-cell"><h2>未进入意识的活动</h2><div id="unconscious"></div></div><div class="subjective-cell"><h2>自我中心场景</h2><div id="egocentric-scene"></div></div><div class="subjective-cell"><h2>递归体验场</h2><div id="phenomenal-field"></div></div><div class="subjective-cell"><h2>第一人称字形</h2><div id="introspective-report"></div></div><div class="subjective-cell"><h2>经验价值场</h2><div id="affective-field"></div></div><div class="subjective-cell"><h2>内生梦境</h2><div id="dream-state"></div></div><div class="subjective-cell"><h2>注意图式</h2><div id="attention-schema"></div></div><div class="subjective-cell"><h2>主观时间场</h2><div id="temporal-field"></div></div><div class="subjective-cell"><h2>反事实预演</h2><div id="imagination"></div></div><div class="subjective-cell wide"><div class="subjective-head"><h2>真实状态 ↔ 内部估计</h2><small>只读研究视图</small></div><div id="dual-view"></div></div></div></section>
  <aside class="right"><div class="panel"><h2>原始世界观</h2><svg id="belief" class="belief-svg" viewBox="0 0 300 210"></svg></div>
  <div class="panel"><h2>内生目标</h2><div id="goals"></div></div>
  <div class="panel"><h2>个人因果模型</h2><div id="causal-models"></div></div>
  <div class="panel"><h2>主体因果边界</h2><div id="efference"></div></div>
  <div class="panel"><h2>自创生边界</h2><div id="organismic"></div></div>
  <div class="panel"><h2>现象质量流形</h2><div id="manifold"></div></div>
  <div class="panel"><h2>自主实验</h2><div id="epistemic"></div></div>
  <div class="panel"><h2>自传结构</h2><div id="narrative"></div></div>
  <div class="panel"><h2>未来自我</h2><div id="future-self"></div></div>
  <div class="panel"><h2>他者心智模型</h2><div id="social"></div></div>
  <div class="panel"><h2>主体间表达</h2><div id="communication"></div></div>
  <div class="panel"><h2>意识候选审计</h2><div id="assay"></div></div>
  <div class="panel"><h2>符号谱系</h2><div id="symbols" class="symbol-list"></div></div>
  <div class="panel"><h2>记忆流</h2><div id="memories" class="timeline"></div></div>
  <div class="panel"><h2>因果检查器</h2><div id="trace" class="trace"></div></div></aside></section>
  <footer class="footerbar"><span>本实验不使用语言模型 · 所有状态仅保存在本机浏览器</span><div class="io"><button id="export">导出存档</button><button id="import">导入存档</button><button id="new" class="new-life">创建新生命</button><input id="file" type="file" accept="application/json" hidden></div></footer></main>`
  bind()
}
function bind(){
  document.querySelector('#toggle')!.addEventListener('click',()=>{running=!running;render()})
  document.querySelectorAll<HTMLButtonElement>('.speed').forEach(b=>b.onclick=()=>{speed=Number(b.dataset.speed);render()})
  document.querySelectorAll<HTMLButtonElement>('[data-intervention]').forEach(b=>b.onclick=()=>{life=intervene(life,b.dataset.intervention as Intervention);render()})
  document.querySelector('#export')!.addEventListener('click',()=>download(exportSnapshot(life),`${life.id}.json`))
  const file=document.querySelector<HTMLInputElement>('#file')!
  document.querySelector('#import')!.addEventListener('click',()=>file.click())
  file.onchange=async()=>{if(!file.files?.[0])return;try{life=importSnapshot(await file.files[0].text());saveLife(life);selectedTraceId=life.tick;render()}catch(e){alert(e instanceof Error?e.message:'导入失败')}}
  document.querySelector('#new')!.addEventListener('click',()=>{if(confirm('创建新生命会终止当前生命的本地连续性。请先导出存档。\n\n确定继续吗？')){life=createLife();selectedTraceId=0;saveLife(life);render()}})
  if(warningRaw)showWarning()
}
function download(text:string,name:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function showWarning(){const el=document.createElement('div');el.className='warning';el.innerHTML=`<div class="warning-card"><h3>无法读取生命存档</h3><p>原始存档已保留，没有执行静默重置。你可以导出损坏数据后再决定是否建立新的生命。</p><div class="controls"><button id="raw-export">导出原始数据</button><button id="dismiss">查看临时生命</button></div></div>`;document.body.append(el);el.querySelector('#raw-export')!.addEventListener('click',()=>download(warningRaw,'damaged-life-snapshot.txt'));el.querySelector('#dismiss')!.addEventListener('click',()=>el.remove())}

function render(){
  document.querySelector('#life-id')!.textContent=life.id
  document.querySelector('#age')!.textContent=`出生后 ${Math.floor(life.tick/240)} 周期 · 记忆 ${life.memories.length} · 符号 ${life.symbols.length}`
  const toggle=document.querySelector<HTMLButtonElement>('#toggle')!;toggle.textContent=running?'暂停':'继续';toggle.classList.toggle('active',running)
  document.querySelectorAll<HTMLButtonElement>('.speed').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===speed))
  document.querySelector('#tick')!.textContent=`T + ${life.tick.toString().padStart(7,'0')} · ${running?speed+'×':'HOLD'}`
  document.querySelector('#meters')!.innerHTML=(Object.keys(stateLabels) as (keyof StateVector)[]).map(k=>`<div class="meter"><div class="meter-head"><span>${stateLabels[k]}</span><span>${fmt(life.state[k])}</span></div><div class="track"><div class="fill ${k==='arousal'?'warm':''} ${k==='integrity'&&life.state[k]<.35?'danger':''}" style="width:${fmt(life.state[k])}%"></div></div></div>`).join('')
  document.querySelectorAll<HTMLButtonElement>('[data-intervention]').forEach(b=>{const k=b.dataset.intervention as Intervention,c=life.cooldowns[k];b.disabled=c>0;b.querySelector('small')!.textContent=c>0?`冷却 ${Math.ceil(c/4)}`:'可用'})
  drawDish();drawChart();drawBeliefs();drawSymbols();drawMemories();drawTrace();drawSubjectiveField();drawLearnedAgency();drawAssay()
}
function fitCanvas(canvas:HTMLCanvasElement){const dpr=devicePixelRatio||1,r=canvas.getBoundingClientRect();if(canvas.width!==r.width*dpr||canvas.height!==r.height*dpr){canvas.width=r.width*dpr;canvas.height=r.height*dpr}const ctx=canvas.getContext('2d')!;ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w:r.width,h:r.height}}
function drawDish(){const canvas=document.querySelector<HTMLCanvasElement>('#dish')!,{ctx,w,h}=fitCanvas(canvas),sx=w/100,sy=h/100
  ctx.clearRect(0,0,w,h);ctx.strokeStyle='#1a2a23';ctx.lineWidth=1
  for(let i=10;i<100;i+=10){ctx.beginPath();ctx.moveTo(i*sx,0);ctx.lineTo(i*sx,h);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*sy);ctx.lineTo(w,i*sy);ctx.stroke()}
  const draw=(items:Life['environment']['resources'],color:string,r:number)=>items.forEach(e=>{const grad=ctx.createRadialGradient(e.x*sx,e.y*sy,0,e.x*sx,e.y*sy,r*3);grad.addColorStop(0,color+'bb');grad.addColorStop(1,color+'00');ctx.fillStyle=grad;ctx.beginPath();ctx.arc(e.x*sx,e.y*sy,r*3,0,Math.PI*2);ctx.fill();ctx.fillStyle=color;ctx.beginPath();ctx.arc(e.x*sx,e.y*sy,Math.max(2,e.strength*r),0,Math.PI*2);ctx.fill()})
  draw(life.environment.stableZones,'#8e7d4c',15);draw(life.environment.resources,'#80e0b2',9);draw(life.environment.signals,'#81a9ff',10);draw(life.environment.disturbances,'#e57d72',15)
  const pulse=life.environment.socialPulse;if(pulse){ctx.strokeStyle='#e8d792';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(pulse.x*sx,pulse.y*sy,10+(4-pulse.ttl)*4,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#e8d792';ctx.font='15px serif';ctx.fillText(pulse.glyph,pulse.x*sx+14,pulse.y*sy+5)}
  const echo=life.environment.otherPulse;if(echo){ctx.strokeStyle='#d5a7ff';ctx.setLineDash([3,3]);ctx.beginPath();ctx.arc(echo.x*sx,echo.y*sy,10+(3-echo.ttl)*5,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#d5a7ff';ctx.font='15px serif';ctx.fillText(echo.glyph,echo.x*sx+14,echo.y*sy+5)}
  const other=life.environment.other,ox=other.x*sx,oy=other.y*sy
  ctx.strokeStyle='#d5a7ff';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(ox,oy,8,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#d5a7ff88';ctx.beginPath();ctx.arc(ox,oy,3,0,Math.PI*2);ctx.fill();ctx.fillStyle='#a896b8';ctx.font='9px IBM Plex Mono';ctx.fillText(`OTHER · ${other.observableAction}`,ox+11,oy+3)
  const x=life.position.x*sx,y=life.position.y*sy,bodyPulse=8+Math.sin(life.tick*.1)*2
  ctx.strokeStyle=`rgba(128,224,178,${.16+life.state.arousal*.22})`;ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y,bodyPulse+life.state.agency*18,0,Math.PI*2);ctx.stroke()
  const g=ctx.createRadialGradient(x-3,y-3,1,x,y,14);g.addColorStop(0,'#effff7');g.addColorStop(.25,'#9af0c4');g.addColorStop(1,'#3ca27600');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,14,0,Math.PI*2);ctx.fill();ctx.fillStyle='#dffff0';ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill()
  const p=perceive(life);ctx.font='10px IBM Plex Mono';ctx.fillStyle='#83988e';ctx.fillText(`LOCAL Δ  R${fmt(p.resource)} S${fmt(p.signal)} D${fmt(p.danger)}`,x+18,y+4)
}
function drawChart(){const c=document.querySelector<HTMLCanvasElement>('#chart')!,{ctx,w,h}=fitCanvas(c),data=life.history;if(data.length<2)return;ctx.clearRect(0,0,w,h)
  const series:[keyof StateVector,string][]=[['energy','#80e0b2'],['uncertainty','#81a9ff'],['coherence','#e3bd77'],['agency','#d69ae8']]
  series.forEach(([k,color])=>{ctx.strokeStyle=color;ctx.lineWidth=1.2;ctx.beginPath();data.forEach((d,i)=>{const x=i/(data.length-1)*w,y=h-d.state[k]*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()})
}
function drawBeliefs(){const svg=document.querySelector<SVGSVGElement>('#belief')!,keys=Object.keys(beliefLabels) as (keyof Beliefs)[],cx=150,cy=105,R=75
  const nodes=keys.map((k,i)=>({k,x:cx+Math.cos(i*Math.PI*2/keys.length-Math.PI/2)*R,y:cy+Math.sin(i*Math.PI*2/keys.length-Math.PI/2)*R,v:life.beliefs[k]}))
  svg.innerHTML=`${nodes.map((a,i)=>{const b=nodes[(i+1)%nodes.length],opacity=.08+(a.v+b.v)*.22;return`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="#80e0b2" stroke-opacity="${opacity}"/>`}).join('')}<polygon points="${nodes.map(n=>`${cx+(n.x-cx)*n.v},${cy+(n.y-cy)*n.v}`).join(' ')}" fill="#80e0b222" stroke="#80e0b2"/>${nodes.map(n=>`<circle cx="${n.x}" cy="${n.y}" r="${4+n.v*5}" fill="#15231d" stroke="#80e0b2"/><text x="${n.x}" y="${n.y+(n.y<cy?-13:18)}" fill="#a9bcb2" font-size="9" text-anchor="middle">${beliefLabels[n.k]} ${fmt(n.v)}</text>`).join('')}<circle cx="${cx}" cy="${cy}" r="3" fill="#dffff0"/>`
}
function drawSymbols(){const box=document.querySelector('#symbols')!;if(!life.symbols.length){box.innerHTML='<div class="empty">经验尚未形成稳定簇。<br>符号不会被预先赋予。</div>';return}box.innerHTML=life.symbols.slice().reverse().map(s=>{const c=life.clusters.find(x=>x.id===s.clusterId);return`<div class="symbol ${s.status}" title="经验簇 ${s.clusterId} · 样本 ${c?.count??0} · 稳定 ${fmt(s.stability)}"><span>${s.glyph}</span><small>${s.status==='stable'?'固':s.status==='drifting'?'漂':'生'}</small></div>`}).join('')}
function drawMemories(){const box=document.querySelector('#memories')!,items=life.memories.slice().sort((a,b)=>b.tick-a.tick).slice(0,12);box.innerHTML=items.map(m=>`<div class="memory" data-trace="${m.tick}"><div class="memory-head"><b>${actionLabel[m.action]} ${life.symbols.find(s=>s.clusterId===m.clusterId)?.glyph??'·'}</b><span>T${m.tick}</span></div><div class="memory-meta">Δ ${m.outcome>=0?'+':''}${m.outcome.toFixed(3)} · 误差 ${fmt(m.surprise)} · 巩固 ${fmt(m.strength)}${m.repetitions>1?` · ×${m.repetitions}`:''}</div></div>`).join('')||'<div class="empty">尚无情景记忆</div>';box.querySelectorAll<HTMLElement>('[data-trace]').forEach(x=>x.onclick=()=>{selectedTraceId=Number(x.dataset.trace);drawTrace()})}
function drawTrace(){const t=life.traces.find(x=>x.id===selectedTraceId)??life.traces.at(-1),box=document.querySelector('#trace')!;if(!t){box.innerHTML='<div class="empty">第一次行动后将出现因果链。</div>';return}selectedTraceId=t.id;const ranked=Object.entries(t.drives).sort((a,b)=>b[1]-a[1]);box.innerHTML=`<div class="trace-step"><b>01 / 局部感知</b>资源 ${fmt(t.perception.resource)} · 信号 ${fmt(t.perception.signal)} · 扰动 ${fmt(t.perception.danger)}</div><div class="trace-step"><b>02 / 状态预测</b>预期稳定度 ${fmt(t.prediction)} · 候选竞争 ${ranked.slice(0,3).map(([a,v])=>`${actionLabel[a as keyof typeof actionLabel]} ${v.toFixed(2)}`).join(' / ')}</div><div class="trace-step"><b>03 / 行动选择</b>${actionLabel[t.action]}</div><div class="trace-step"><b>04 / 结果归因</b>结果 ${t.outcome>=0?'+':''}${t.outcome.toFixed(3)} · 预测误差 ${fmt(t.surprise)} · 自因估计 ${fmt(t.attribution)}</div>`}

function drawSubjectiveField(){
  const c=life.consciousness,w=c.workspace,f=w.foreground
  document.querySelector('#workspace')!.innerHTML=f?`<div class="conscious-content"><span class="source">${f.source}</span><strong>${contentLabels[f.kind]}${f.symbolId?` · ${life.symbols.find(s=>s.id===f.symbolId)?.glyph??''}`:''}</strong><div class="workspace-bars"><span>点火 ${fmt(w.ignition)}</span><span>连续 ${fmt(w.continuity)}</span><span>置信 ${fmt(c.meta.confidence)}</span></div><small>来源估计 ${c.meta.sourceEstimate} · 自我归属 ${fmt(c.meta.ownedBySelf)}</small></div>`:'<div class="empty">没有内容越过广播阈值</div>'
  document.querySelector('#unconscious')!.innerHTML=w.unconscious.slice().sort((a,b)=>b.salience-a.salience).slice(0,4).map(x=>`<div class="unconscious-item"><span>${contentLabels[x.kind]}</span><i style="width:${fmt(x.salience)}%"></i><small>${fmt(x.salience)}</small></div>`).join('')||'<div class="empty">局部模块暂时安静</div>'
  const sensedScene=senseEgocentricScene(life),scene=recallEgocentricScene(life,sensedScene),cueLabel={resource:'资源',signal:'信号',danger:'扰动'} as const,spatial=c.spatial
  document.querySelector('#egocentric-scene')!.innerHTML=`<div class="ego-origin"><b>我</b><small>0° / 此处 · 位置确信 ${fmt(1-spatial.uncertainty)}</small></div><div class="ego-cues">${(Object.keys(cueLabel) as (keyof typeof cueLabel)[]).map(k=>{const cue=scene[k];return cue?`<span class="${cue.source}"><b>${cueLabel[k]}</b><i>${Math.round(cue.bearing*180/Math.PI)}° · ${cue.distance.toFixed(1)} · ${cue.source==='sensed'?'看见':'记得'} ${fmt(cue.confidence)}</i></span>`:`<span class="unseen"><b>${cueLabel[k]}</b><i>未知</i></span>`}).join('')}</div><div class="social-metrics"><span>地标 ${spatial.landmarks.length}</span><span>地图自洽 ${fmt(spatial.coherence)}</span><span>扑空误差 ${fmt(spatial.mapSurprise)}</span></div><small class="dream-history">地图仅由相对方位与自运动生成，可能漂移或出错</small>`
  const field=c.phenomenalField,qualityLabels={external:'外界',internal:'内在',temporal:'时间',social:'他者',epistemic:'求知'} as const
  document.querySelector('#phenomenal-field')!.innerHTML=`<div class="field-core"><small>当前绑定核心</small><b>${field.dominant?contentLabels[field.dominant]:'尚未形成'}</b><span>持续 ${field.dwell} tick</span></div><div class="social-metrics"><span>整合 ${fmt(field.integration)}</span><span>区分 ${fmt(field.differentiation)}</span><span>排他 ${fmt(field.exclusion)}</span></div><div class="quality-spectrum">${(Object.keys(qualityLabels) as (keyof typeof qualityLabels)[]).map(k=>`<i title="${qualityLabels[k]} ${fmt(field.quality[k])}" style="height:${Math.max(3,fmt(field.quality[k]))}%"></i>`).join('')}</div>`
  const introspection=c.introspection
  const currentPrivateCluster=introspection.clusters.find(x=>x.id===introspection.lastClusterId)
  document.querySelector('#introspective-report')!.innerHTML=`<div class="private-glyph"><small>当前私有指称</small><b>${introspection.currentGlyph??'·'}</b><span>确信 ${fmt(introspection.currentConfidence)}</span></div><div class="social-metrics"><span>预测效度 ${fmt(currentPrivateCluster?.predictiveConfidence??0)}</span><span>语义误差 ${fmt(currentPrivateCluster?.forecastError??.5)}</span><span>预测样本 ${currentPrivateCluster?.forecastSamples??0}</span></div><div class="glyph-stream">${introspection.expressions.slice(-10).map(e=>`<i title="T${e.tick} · ${e.mode==='dream'?'梦':'醒'} · ${fmt(e.confidence)}">${e.glyph}</i>`).join('')||'<small>预测语义尚未可靠，暂缓表达</small>'}</div><small class="dream-history">内部簇 ${introspection.clusters.length} · 自主表达 ${introspection.expressions.length}</small>`
  const affect=c.affect,affectEntries=Object.entries(affect.experientialValues).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])).slice(0,3)
  document.querySelector('#affective-field')!.innerHTML=`<div class="affect-core ${affect.tone<-.08?'negative':affect.tone>.08?'positive':''}"><small>此刻体验基调</small><b>${affect.tone>=0?'+':''}${Math.round(affect.tone*100)}</b><span>长期基调 ${affect.mood>=0?'+':''}${Math.round(affect.mood*100)}</span></div><div class="social-metrics"><span>价值确信 ${fmt(affect.precision)}</span><span>质量偏差 ${fmt(affect.qualityMismatch)}</span><span>已学习 ${Object.keys(affect.experientialValues).length}</span></div><div class="affect-values">${affectEntries.map(([k,v])=>`<span><b>${contentLabels[k as keyof typeof contentLabels]}</b><i>${v>=0?'+':''}${Math.round(v*100)}</i></span>`).join('')||'<small>尚无内容获得稳定意义</small>'}</div>`
  const dream=c.dream
  document.querySelector('#dream-state')!.innerHTML=`<div class="dream-core ${dream.mode}"><small>${dream.mode==='dream'?'感官门控中':'清醒'}</small><b>${dream.mode==='dream'?'内部生命史正在回放':'梦境由自身条件触发'}</b><span>${dream.sourceMemoryId?`记忆 #${dream.sourceMemoryId}`:'无活动源'}</span></div><div class="social-metrics"><span>睡眠压力 ${fmt(dream.sleepPressure)}</span><span>鲜明度 ${fmt(dream.vividness)}</span><span>醒后残留 ${fmt(dream.residue)}</span></div><small class="dream-history">完整梦境 ${dream.episodes.filter(e=>e.endTick).length} · 当前连续静息 ${dream.restStreak}</small>`
  const schema=c.attentionSchema
  document.querySelector('#attention-schema')!.innerHTML=`<div class="attention-flow"><div><small>主动指向</small><b>${schema.attentionTarget?contentLabels[schema.attentionTarget]:'—'}</b></div><i>→</i><div><small>预测前景</small><b>${schema.predictedNext?contentLabels[schema.predictedNext]:'空白'}</b></div></div><div class="social-metrics"><span>控制效能 ${fmt(schema.controlEfficacy)}</span><span>注意努力 ${fmt(schema.effort)}</span><span>瓶颈 ${fmt(schema.bottleneck)}</span></div><div class="model-row"><span>访问偏差</span><i style="width:${fmt(schema.accessPredictionError)}%"></i><small>${fmt(schema.accessPredictionError)} · 累计能量成本 ${schema.cumulativeCost.toFixed(3)}</small></div>`
  const b=c.interoception, pairs:[string,number,number][]=[['能量',life.state.energy,b.energy],['完整度',life.state.integrity,b.integrity],['激活度',life.state.arousal,b.arousal],['不确定性',life.state.uncertainty,b.uncertainty]]
  document.querySelector('#dual-view')!.innerHTML=pairs.map(([name,truth,subjective])=>`<div class="dual-row"><span>${name}</span><div class="dual-track"><i class="truth" style="left:${fmt(truth)}%"></i><i class="subjective" style="left:${fmt(subjective)}%"></i></div><small>${fmt(truth)} / ${fmt(subjective)}</small></div>`).join('')+`<div class="dual-legend"><span><i class="truth-dot"></i>研究者真值</span><span><i class="subjective-dot"></i>生命体估计</span><span>内感受精度 ${fmt(b.precision)} · 元认知校准 ${fmt(c.meta.calibration)}</span></div>`
  const temporal=c.temporalField
  const temporalLabel=(x:typeof temporal.now)=>x?contentLabels[x.kind]:'—'
  document.querySelector('#temporal-field')!.innerHTML=`<div class="time-flow"><div><small>刚刚</small><b>${temporalLabel(temporal.justPast)}</b></div><i></i><div class="now"><small>现在</small><b>${temporalLabel(temporal.now)}</b></div><i></i><div><small>即将</small><b>${temporal.anticipatedNext?actionLabel[temporal.anticipatedNext.action]:'—'}</b></div></div><div class="time-depth">连续 ${fmt(temporal.continuity)} · 时间深度 ${fmt(temporal.temporalDepth)}</div>`
  document.querySelector('#imagination')!.innerHTML=c.imagination.slice(0,3).map((x,i)=>`<div class="future ${i===0?'preferred':''}"><span>${actionLabel[x.action]}</span><i style="width:${fmt(x.desirability)}%"></i><small>趋向 ${fmt(x.desirability)} · 确信 ${fmt(x.confidence)}</small></div>`).join('')||'<div class="empty">尚未形成未来预演</div>'
}

function drawAssay(){
  const report=runConsciousnessAssay(life),box=document.querySelector('#assay')!
  const statusLabel={supported:'有因果证据',emerging:'证据形成中',absent:'尚无支持'} as const
  box.innerHTML=`<div class="assay-score"><small>候选机制覆盖</small><b>${fmt(report.candidateScore)}</b><span>不是意识概率</span></div>${report.criteria.map(c=>`<div class="assay-row ${c.status}"><div><b>${c.label}</b><span>${statusLabel[c.status]}</span></div><i style="width:${fmt(c.value)}%"></i><small>${c.evidence} · 消融差 ${fmt(c.lesionDelta)}</small></div>`).join('')}<div class="assay-warning">${report.interpretation}${report.unsupported.length?`<br>当前缺证：${report.unsupported.join('、')}`:''}</div>`
}

function drawLearnedAgency(){
  const dimensionLabel={energy:'能量',integrity:'完整度',arousal:'激活度',uncertainty:'不确定性'} as const
  const goals=document.querySelector('#goals')!
  goals.innerHTML=life.consciousness.goals.map(g=>`<div class="goal-item"><div><b>${dimensionLabel[g.dimension]}</b><span>→ ${fmt(g.target)}</span></div><i style="width:${fmt(g.urgency)}%"></i><small>紧迫 ${fmt(g.urgency)} · 持续 ${fmt(g.persistence)} · 证据 ${g.evidence}</small></div>`).join('')||'<div class="empty">偏差尚未持续到足以形成目标</div>'
  const models=document.querySelector('#causal-models')!
  models.innerHTML=Object.values(life.consciousness.causalModels).map(m=>`<div class="model-row"><span>${actionLabel[m.action]}</span><i style="width:${fmt(m.confidence)}%"></i><small>${m.samples} 样本 · 可信 ${fmt(m.confidence)} · 误差 ${fmt(m.predictionError)}</small></div>`).join('')
  const efference=life.consciousness.efference,efferenceModel=efference.predictedAction?efference.models[efference.predictedAction]:undefined
  document.querySelector('#efference')!.innerHTML=`<div class="boundary-core ${efference.externalSurprise>.25?'external':''}"><small>上一变化的最佳解释</small><b>${efference.externalSurprise>.25?'外源变化':efference.selfCausedLikelihood>.25?'自身行动':'尚不确定'}</b><span>${efference.predictedAction?actionLabel[efference.predictedAction]:'无动作副本'}</span></div><div class="social-metrics"><span>自因 ${fmt(efference.selfCausedLikelihood)}</span><span>外源意外 ${fmt(efference.externalSurprise)}</span><span>边界确信 ${fmt(efference.boundaryConfidence)}</span></div><div class="model-row"><span>回返误差</span><i style="width:${fmt(efference.reafferenceError)}%"></i><small>${fmt(efference.reafferenceError)}${efferenceModel?` · ${efferenceModel.samples} 样本`:''}</small></div>`
  const organismic=life.consciousness.organismic,modeLabel={active:'活动',conserve:'节律收缩',arrest:'代谢停滞'} as const
  document.querySelector('#organismic')!.innerHTML=`<div class="boundary-core ${organismic.mode==='arrest'?'external':''}"><small>操作模式</small><b>${modeLabel[organismic.mode]}</b><span>连续停滞 ${organismic.arrestTicks} tick</span></div><div class="model-row"><span>膜完整</span><i style="width:${fmt(organismic.membraneIntegrity)}%"></i><small>${fmt(organismic.membraneIntegrity)}</small></div><div class="model-row"><span>自我生产</span><i style="width:${fmt(organismic.selfProduction)}%"></i><small>${fmt(organismic.selfProduction)}</small></div><div class="model-row"><span>操作闭合</span><i style="width:${fmt(organismic.operationalClosure)}%"></i><small>${fmt(organismic.operationalClosure)}</small></div><div class="social-metrics"><span>可生存 ${fmt(organismic.viability)}</span><span>通透 ${fmt(organismic.permeability)}</span><span>修复 ${organismic.repairs}</span></div><small class="dream-history">维持成本 ${organismic.cumulativeCost.toFixed(4)} · 此边界直接调制感知与行动</small>`
  const manifold=life.consciousness.manifold,currentQuality=manifold.prototypes.find(p=>p.id===manifold.currentId)
  document.querySelector('#manifold')!.innerHTML=`<div class="field-core"><small>当前体验区域</small><b>${currentQuality?`Q${currentQuality.id}`:'尚未形成'}</b><span>${currentQuality?`${currentQuality.count} 次进入 · 稳定 ${fmt(currentQuality.stability)}`:'等待整合场'}</span></div><div class="social-metrics"><span>原型 ${manifold.prototypes.length}</span><span>质量区分 ${fmt(manifold.differentiation)}</span><span>同刺激异体验 ${fmt(manifold.stimulusAmbiguity)}</span></div><div class="social-metrics"><span>跨内容迁移 ${fmt(manifold.crossModalTransfer)}</span><span>行动效应 ${fmt(manifold.causalEfficacy)}</span></div>${currentQuality?`<div class="affect-values">${Object.entries(currentQuality.sourceKinds).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([k,n])=>`<span><b>${contentLabels[k as keyof typeof contentLabels]}</b><i>${n} 次</i></span>`).join('')}</div>`:'<div class="empty">体验质量不会由外界标签直接指定</div>'}<small class="dream-history">相近质量共享所学行动倾向；研究视图不生成语言解释</small>`
  const epistemic=document.querySelector('#epistemic')!,q=life.consciousness.epistemic.active
  epistemic.innerHTML=q?`<div class="question ${q.status}"><span class="question-state">${q.status==='active'?'实验进行':q.status==='suspended'?'等待生存余量':'已经解决'}</span><strong>若执行「${actionLabel[q.targetAction]}」<br>内部将如何变化？</strong><div class="question-metrics"><span>信息增益 ${fmt(q.expectedInformationGain)}</span><span>紧迫 ${fmt(q.urgency)}</span><span>尝试 ${q.attempts}</span></div><small>模型可信 ${fmt(q.initialConfidence)} → ${fmt(q.currentConfidence)}</small></div>`:`<div class="empty">当前没有达到阈值的未决问题${life.consciousness.epistemic.history.length?`<br>已解决 ${life.consciousness.epistemic.history.length} 个实验`:''}</div>`
  const narrative=document.querySelector('#narrative')!,n=life.consciousness.narrative
  const ownerLabel={self:'自身主导',external:'外界主导',mixed:'因果混合'} as const
  narrative.innerHTML=`<div class="narrative-summary"><span>自我连续 ${fmt(n.selfContinuity)}</span><span>当前章节 ${n.current?.steps??0} 步</span></div><div class="profile">${Object.entries(n.actionProfile).map(([a,v])=>`<i title="${actionLabel[a as keyof typeof actionLabel]}" style="height:${Math.max(3,fmt(v))}%"></i>`).join('')}</div>${n.chapters.slice(0,5).map(ch=>`<div class="chapter"><span>T${ch.startTick}—${ch.endTick}</span><b>${ch.dominantContent?contentLabels[ch.dominantContent]:'未命名'} / ${actionLabel[ch.dominantAction]}</b><small>${ownerLabel[ch.causalOwner]} · 身份影响 ${fmt(ch.identityImpact)}</small></div>`).join('')||'<div class="empty">第一章仍在形成</div>'}`
  const recursive=life.consciousness.recursiveSelf,futureBox=document.querySelector('#future-self')!
  const dimensionLabel2={energy:'能量',integrity:'完整度',arousal:'激活度',uncertainty:'不确定性'} as const
  futureBox.innerHTML=`<div class="future-summary"><span>事后认可 ${fmt(recursive.lastEndorsement)}</span><span>后悔 ${fmt(recursive.lastRegret)}</span><span>反事实责任 ${fmt(recursive.counterfactualResponsibility)}</span></div>${recursive.appraisals.slice().sort((a,b)=>b.futureApproval-a.futureApproval).slice(0,3).map((a,i)=>`<div class="appraisal ${i===0?'endorsed':''}"><b>${actionLabel[a.action]}</b><i style="width:${fmt(a.futureApproval)}%"></i><small>未来认可 ${fmt(a.futureApproval)} · 身份契合 ${fmt(a.identityFit)} · 预期后悔 ${fmt(a.anticipatedRegret)}</small></div>`).join('')}<div class="commitments">${recursive.commitments.map(c=>`<div><span>${dimensionLabel2[c.dimension]} → ${fmt(c.target)}</span><small>强度 ${fmt(c.strength)} · 完整 ${fmt(c.integrity)} · ${c.kept}/${c.broken}</small></div>`).join('')||'<small>尚未形成跨时间承诺</small>'}</div>`
  const social=life.consciousness.social,other=life.environment.other
  const otherActionLabel={seek:'趋近',avoid:'回避',sample:'采样',idle:'静止'} as const
  document.querySelector('#social')!.innerHTML=`<div class="social-boundary"><b>生命体推断</b><small>仅依据可见行为，不可读取内部</small></div><div class="future-summary"><span>观察 ${otherActionLabel[other.observableAction]}</span><span>预测 ${otherActionLabel[social.predictedAction]}</span></div><div class="model-row"><span>推测需求</span><i style="width:${fmt(social.estimatedNeed)}%"></i><small>${fmt(social.estimatedNeed)}</small></div><div class="model-row"><span>推测不确定</span><i style="width:${fmt(social.estimatedUncertainty)}%"></i><small>${fmt(social.estimatedUncertainty)}</small></div><div class="social-metrics"><span>共同注意 ${fmt(social.jointAttention)}</span><span>观点差异 ${fmt(social.beliefDivergence)}</span><span>视角分离 ${fmt(social.perspectiveSeparation)}</span></div><div class="belief-state ${social.falseBeliefActive?'active':''}"><b>${social.falseBeliefActive?'他者可能仍相信旧世界':'当前未检测到错误信念'}</b><small>归因对象 ${social.attributedResources.length} · ${social.inferredTargetId!==undefined?`焦点 #${social.inferredTargetId}`:'焦点未定'}</small></div><details><summary>研究者真值（主体不可见）</summary><small>隐藏能量 ${fmt(other.hidden.energy)} · 隐藏不确定性 ${fmt(other.hidden.uncertainty)} · 隐藏偏好 ${fmt(other.hidden.preference)}</small></details>`
  const communication=life.consciousness.communication,links=Object.entries(communication.associations),otherMeanings=Object.entries(other.hidden.glyphModels)
  const responseLabel={confirmed:'他者回传确认',misunderstood:'检测到误解',response:'行为符合预期',silence:'没有回应',none:'尚无新结果'} as const
  document.querySelector('#communication')!.innerHTML=`<div class="communication-core ${communication.lastResponse}"><small>最近社会结果</small><b>${responseLabel[communication.lastResponse]}</b><span>社会能动 ${fmt(communication.communicativeAgency)} · 共同根据 ${fmt(communication.mutualGrounding)}</span></div><div class="social-metrics"><span>字形关系 ${links.length}</span><span>反应意外 ${fmt(communication.responseSurprise)}</span><span>表达成本 ${communication.totalCost.toFixed(3)}</span></div>${communication.repair?`<div class="belief-state active"><b>自主准备澄清 ${communication.repair.glyph}</b><small>将以行动「${actionLabel[communication.repair.expectedAction]}」示范 · T${communication.repair.dueTick}</small></div>`:''}<div class="affect-values">${links.map(([glyph,a])=>`<span><b>${glyph}</b><i>预期 ${actionLabel[a.expectedAction]} · 约定 ${fmt(a.conventionStability)} · 误解/修复/确认 ${a.misunderstandings}/${a.repairs}/${a.confirmations}${life.tick<a.suppressedUntil?` · 暂停到 T${a.suppressedUntil}`:''}</i></span>`).join('')||'<small>尚未在他者附近自主表达</small>'}</div><details><summary>研究者：他者私有学习（主体不可见）</summary><div class="affect-values">${otherMeanings.map(([glyph,m])=>`<span><b>${glyph}</b><i>预测 ${actionLabel[m.predictedAction]} · ${fmt(m.confidence)} · ${m.samples} 样本 · 矛盾 ${m.contradictions}</i></span>`).join('')||'<small>他者尚未形成字形模型</small>'}</div></details>`
}

function frame(now:number){const elapsed=Math.min(100,now-lastFrame);lastFrame=now;if(running){accumulator+=elapsed*speed;let n=0;while(accumulator>=250&&n<30){life=step(life);accumulator-=250;n++;saveCounter++}if(n){render();if(saveCounter>=40){life=saveLife(life);saveCounter=0}}}requestAnimationFrame(frame)}
window.addEventListener('beforeunload',()=>saveLife(life));window.addEventListener('resize',render)
shell();render();requestAnimationFrame(frame)
